# Site settings
title: Hugrún
email: gedfraedsla@gedfraedsla.is
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gedfraedsla.is" # the base hostname & protocol for your site
twitter_username: gedfraedsla
facebook_username: gedfraedsla

# Build settings
markdown: redcarpet

permalink: pretty

collections:
  posts:
    output: true
    permalink: pretty

  pages:
    permalink: pretty

  greinar:
    permalink: pretty
